server:
  port: 9001
mybatis:
  type-aliases-package: com.atguigu.springcloud.entities
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml
spring:
  application:
    name: microservicecloud-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/cloudDB01
    username: root
    password: 123456
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: microservicecloud-dept9001
    prefer-ip-address: true

info:
  app.name: atguigu.microservicecloud
  company.name: www.atguigu.com
  build.artifactId: microservicecloud-provider-dept-9001
  build.version: 0.0.1-SNAPSHOT